# Generated by Django 2.2 on 2019-04-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0002_auto_20190426_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_number', models.TextField()),
                ('date_d', models.DateField()),
                ('Category', models.TextField()),
                ('Company', models.TextField()),
                ('Spent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('domain', models.TextField()),
            ],
        ),
    ]
