# Generated by Django 2.2 on 2019-04-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_bill_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
