# Generated by Django 2.2 on 2019-04-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_delete_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
